timeout: 14400s

#### SECURITY NOTICE ####
# Google Cloud Build (GCB) supports the usage of secrets for build requests.
# Secrets appear within GCB configs as base64-encoded strings.
# These secrets are GCP Cloud KMS-encrypted and cannot be decrypted by any human or system
# outside of GCP Cloud KMS for the GCP project this encrypted resource was created for.
# Seeing the base64-encoded encrypted blob here is not a security event for the project.
#
# More details on using encrypted resources on Google Cloud Build can be found here:
# https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials
#
# (Please do not remove this security notice.)
secrets:
- kmsKeyName: projects/k8s-staging-release-test/locations/global/keyRings/release/cryptoKeys/encrypt-0
  secretEnv:
    GITHUB_TOKEN: CiQAzX5NM13ZVJOM+E0k629PSa7H5Hkm4mJlPbm7hR8nr67KGAoSUQCmb2uz62tmpa7is9YJx8tlEspVytgq5HAvsd9DWey/oRCsv4VkVBRhnNnlpnmQ8eDPXAaS0GfjrP4KuCgT3mM570N1FH6hTN+u7Yg8uaOxWw==

steps:
- name: gcr.io/cloud-builders/git
  dir: "go/src/k8s.io"
  args:
  - "clone"
  - "--branch=${_TOOL_BRANCH}"
  - "https://github.com/${_TOOL_ORG}/${_TOOL_REPO}"

- name: us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:${_KUBE_CROSS_VERSION}
  dir: "go/src/k8s.io/release"
  env:
  - "GOPATH=/workspace/go"
  - "GOBIN=/workspace/bin"
  - "GO111MODULE=on"
  - "GOPROXY=https://proxy.golang.org"
  - "GOSUMDB=sum.golang.org"
  args:
  - "./compile-release-tools"

- name: gcr.io/k8s-staging-release-test/k8s-cloud-builder:${_KUBE_CROSS_VERSION}
  dir: "go/src/k8s.io/release"
  env:
  - "TOOL_ORG=${_TOOL_ORG}"
  - "TOOL_REPO=${_TOOL_REPO}"
  - "TOOL_BRANCH=${_TOOL_BRANCH}"
  secretEnv:
  - GITHUB_TOKEN
  args:
  - "./anago"
  - "${_RELEASE_BRANCH}"
  - "${_NOMOCK}"
  - "${_OFFICIAL}"
  - "${_BUILDVERSION}"
  - "${_RC}"
  - "--yes"
  - "--gcb"
  - "--basedir=/workspace"
  - "--tmpdir=/workspace/tmp"

tags:
- ${_GCP_USER_TAG}
- ${_RELEASE_BRANCH}
- ${_BUILD_POINT}
- ${_NOMOCK_TAG}
- ${_OFFICIAL_TAG}
- ${_RC_TAG}
- RELEASE
- ${_GIT_TAG}

options:
  machineType: N1_HIGHCPU_32

substitutions:
  # _GIT_TAG will be filled with a git-based tag of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
